export default {
  html: document.querySelector("html"),
  headerBody: document.querySelector("#header-body"),
  collapsableMenu: document.querySelector("#menu-collapse"),
  currentLanguage: document.querySelector(".current-language"),
  menuLinks: document.querySelectorAll(".menu-nav-item"),
  form: document.querySelector("#js-form"),
  select: document.getElementById("countries-select"),
  senderSelect: document.getElementById("sender-select"),
  calcResult: document.querySelector(".calculator-result"),
  overlay: document.querySelector(".overlay"),
  dropdownList: document.querySelector(".languages-dropdown"),
  currentLanguageSection: document.querySelector(".lang-section"),
  calculatorAnchor: document.querySelector(".header-calculator"),
  sizeLabels: document.querySelectorAll(".label-size"),
  controllers: document.querySelector(".calculator-form_controllers"),
  languageSwitcherOptions: document.querySelectorAll(".languages-item"),
  resetForm: document.querySelector(".calculator-reset"),
  calcWeight: document.querySelector(".calculator-weight"),
  calcHeight: document.querySelector(".calculator-height"),
  calcWidth: document.querySelector(".calculator-width"),
  calcLength: document.querySelector(".calculator-length"),
  calcContentValue: document.querySelector(".calculator-content-value"),

  howItWorksAnchor: document.querySelector(".menu-works"),
  faqsAnchor: document.querySelector(".menu-faqs"),
  calcMenuAnchor: document.querySelector(".menu-calc"),
  labelWeight: document.querySelector(".label-weight"),
  labelValue: document.querySelector(".label-value"),
};
