export default {
  form: document.querySelector("#js-form"),
  select: document.getElementById("countries-select"),
  senderSelect: document.getElementById("sender-select"),
  calcResult: document.querySelector(".calculator-result"),
  sizeLabels: document.querySelectorAll(".label-size"),
  resetForm: document.querySelector(".calculator-reset"),
  calcWeight: document.querySelector(".calculator-weight"),
  calcHeight: document.querySelector(".calculator-height"),
  calcWidth: document.querySelector(".calculator-width"),
  calcLength: document.querySelector(".calculator-length"),
  calcContentValue: document.querySelector(".calculator-content-value"),
  labelWeight: document.querySelector(".label-weight"),
  labelValue: document.querySelector(".label-value"),
};
